// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelReservationSystem.Models;

public partial class Account
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string UserRole {get; set;}
}